version: '3.7'

services:
  web:
    build: 
      context: ./web
    volumes:
      - ./web:/home/src/web
      - static_volume:/home/src/web/static
    command:
      - /web/startup.sh
    ports:
      - "8000:8000"
    restart: "on-failure"
    expose:
      - 8000
    env_file:
      - ./.env
    privileged: true
  nginx:
    build: 
      context: ./nginx
    volumes:
      - static_volume:/home/src/web/static
    ports:
      - 1337:80
    depends_on:
      - web
    restart: "on-failure"
  redis:
    build: ./redis
    command: redis-server redis.conf
  celery:
    build:
      context: ./web
    command: celery -A app worker --loglevel=INFO
    volumes:
     - ./web:/home/src/web
  db:
    build: ./postgres 
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - ./.env
volumes:
  static_volume:
  postgres_data:
