version: '3.7'

services:
  web:
    build: 
      context: ./web
    volumes:
      - ./web:/home/src/web
      - static_volume:/home/src/web/static
    ports:
      - "8000:8000"
    restart: "on-failure"
    expose:
      - 8000
    env_file:
      - ./.env
    privileged: true
  nginx:
    build: 
      context: ./nginx
    volumes:
      - static_volume:/home/src/web/static
    ports:
      - 1337:80
    depends_on:
      - web
    restart: "on-failure"
  redis:
    image: redis:alpine
  celery:
    restart: always
    build:
      context: ./web
    command: celery -A app worker -l info
    volumes:
     - ./web:/home/src/web
volumes:
  static_volume:
