version: '3.8'

services:
  web:
    build: 
      context: ./web
    volumes:
      - ./web:/home/src/web
      - static_volume:/home/src/web/static
    command: 
      'gunicorn web.wsgi:application --bind 0.0.0.0:8000 --workers 4 --threads 4'
    ports:
      - "8000:8000"
    restart: "on-failure"
    expose:
      - 8000
    env_file:
      - ./.env
    privileged: true
    depends_on:
      - nginx
      - db
      - celery
  nginx:
    build: 
      context: ./nginx
    volumes:
      - static_volume:/home/src/web/static
    ports:
      - 1337:80
    restart: "on-failure"
  redis:
    build: ./redis
    command: ./redis-server redis.conf
  celery:
    build:
      context: ./web
    volumes:
      - ./web:/home/src/web
    command:
      celery -A web worker --loglevel=INFO
  db:
    build: ./postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - ./.env
volumes:
  static_volume: {}
  postgres_data: {}
